// SPDX-License-Identifier: MIT
// Generated by firmware/tools/p1_registers.py; do not edit by hand.
// Profile P1 for the CC1120 (f_xosc = 32 MHz): values marked P1 are computed with
// the SWRU295E equations, values marked TI come from the SmartRF Studio export in
// TI swrc253e (868 MHz, 2-FSK, 25 kHz, 4 kHz). See firmware/README.md.
#pragma once

#include <stddef.h>
#include <stdint.h>

#include "cc1120.h"

namespace p1 {

using cc1120::RegisterValue;  // {address, value, verifyMask, name}

constexpr uint32_t F_XOSC_HZ = 32000000;
constexpr uint8_t LO_DIVIDER = 4;
constexpr uint32_t CARRIER_HZ = 869525000;
constexpr uint16_t SYMBOL_RATE = 4800;
constexpr uint16_t DEVIATION_HZ = 4000;
constexpr uint16_t RX_FILTER_HZ = 25000;
constexpr int8_t TX_POWER_DBM = 13;
constexpr int8_t RSSI_OFFSET_DB = -99;  // assumed until measured in T4
constexpr int8_t CCA_THRESHOLD_DBM = -100;
constexpr uint8_t MAX_PACKET_BYTES = 103;
constexpr uint8_t DEBT_FACTOR = 12;

constexpr RegisterValue REGISTERS[] = {
    {0x0000, 0xB0, 0xFF, "IOCFG3"},  // TI: GPIO3 not wired: analog pad, high impedance
    {0x0001, 0x06, 0xFF, "IOCFG2"},  // P1: GPIO2 (bench D3) = PKT_SYNC_RXTX, packet on air
    {0x0002, 0xB0, 0xFF, "IOCFG1"},  // TI: GPIO1 is the SPI SO line: analog pad, high impedance
    {0x0003, 0x01, 0xFF, "IOCFG0"},  // P1: GPIO0 (bench D2) = RXFIFO_THR_PKT, end of received packet
    {0x0004, 0xD3, 0xFF, "SYNC3"},  // P1: sync word D3 91 D3 91, byte 3
    {0x0005, 0x91, 0xFF, "SYNC2"},  // P1: sync word byte 2
    {0x0006, 0xD3, 0xFF, "SYNC1"},  // P1: sync word byte 1
    {0x0007, 0x91, 0xFF, "SYNC0"},  // P1: sync word byte 0
    {0x0008, 0x0B, 0xFF, "SYNC_CFG1"},  // TI: sync threshold 11, no PQT gating
    {0x0009, 0x17, 0xFF, "SYNC_CFG0"},  // P1: 32-bit sync word, bit error qualifier off (reset value, explicit)
    {0x000A, 0x06, 0xFF, "DEVIATION_M"},  // P1: DEV_M = 6: deviation 3997.8 Hz (eq. 1)
    {0x000B, 0x0B, 0xFF, "MODCFG_DEV_E"},  // P1: normal modem, 2-GFSK, DEV_E = 3
    {0x000C, 0x1C, 0xFF, "DCFILT_CFG"},  // TI: DC filter for the 25 kHz chain
    {0x000D, 0x28, 0xFF, "PREAMBLE_CFG1"},  // P1: 8 preamble bytes of 0xAA
    {0x000E, 0x2A, 0xFF, "PREAMBLE_CFG0"},  // P1: preamble detector on, PQT 10 (reset value, explicit)
    {0x000F, 0x40, 0xFF, "FREQ_IF_CFG"},  // P1: low IF 62.5 kHz (reset value, explicit); IQIC needs IF > 2 x BW
    {0x0010, 0xC6, 0xFF, "IQIC"},  // TI: image compensation on
    {0x0011, 0x08, 0xFF, "CHAN_BW"},  // P1: ADC_CIC_DECFACT = 0, BB_CIC_DECFACT = 8: RX filter 25.0 kHz (eq. 10)
    {0x0012, 0x46, 0xFF, "MDMCFG1"},  // P1: FIFO mode, NRZ, DVGA 9 dB (reset value, explicit)
    {0x0013, 0x05, 0xFF, "MDMCFG0"},  // TI: data filter off: BW / symbol rate < 10
    {0x0014, 0x63, 0xFF, "SYMBOL_RATE2"},  // P1: SRATE_E = 6, SRATE_M = 0x3A92A: 4800.0 Bd (eq. 6)
    {0x0015, 0xA9, 0xFF, "SYMBOL_RATE1"},  // P1: SRATE_M[15:8]
    {0x0016, 0x2A, 0xFF, "SYMBOL_RATE0"},  // P1: SRATE_M[7:0]
    {0x0017, 0x20, 0xFF, "AGC_REF"},  // TI: AGC reference for 25 kHz
    {0x0018, 0xFF, 0xFF, "AGC_CS_THR"},  // P1: carrier sense at -100 dBm with RSSI offset -99 dB (assumed, T4)
    {0x001C, 0xA9, 0xFF, "AGC_CFG1"},  // TI: freeze gain and RSSI after sync, window 32 samples
    {0x001D, 0xCF, 0xFF, "AGC_CFG0"},  // TI: hysteresis 10 dB
    {0x001E, 0x00, 0xFF, "FIFO_CFG"},  // TI: no CRC autoflush, threshold 0
    {0x0020, 0x03, 0xFF, "SETTLING_CFG"},  // TI: no automatic calibration: manual SCAL per errata
    {0x0021, 0x12, 0xFF, "FS_CFG"},  // P1: lock detector on, 820-960 MHz band (LO divider 4)
    {0x0026, 0x04, 0xFF, "PKT_CFG2"},  // P1: CCA = RSSI below threshold, FIFO packet mode (reset value, explicit)
    {0x0027, 0x01, 0xFF, "PKT_CFG1"},  // P1: no whitening, no address, chip CRC off (P1 CRC differs), status appended
    {0x0028, 0x00, 0xFF, "PKT_CFG0"},  // P1: fixed packet length from PKT_LEN for the test frames; the P1 driver uses variable length (F79)
    {0x0029, 0x3F, 0xFF, "RFEND_CFG1"},  // P1: stay in RX after a packet (receiver always on), no RX timeout
    {0x002B, 0x7D, 0xFF, "PA_CFG2"},  // P1: PA_POWER_RAMP = 61: 13.0 dBm (eq. 21)
    {0x002C, 0x56, 0xFF, "PA_CFG1"},  // TI: ramp 3 symbols (0.625 ms at 4800 Bd)
    {0x002D, 0x7D, 0xFF, "PA_CFG0"},  // TI: upsampler P = 32 for 4.8 kBd (SmartRF Studio export in TI swrc253e, 4.8 kbit/s block)
    {0x002E, 0x67, 0xFF, "PKT_LEN"},  // P1: longest P1 packet LEN + BODY + CRC
    {0x2F00, 0x00, 0xFF, "IF_MIX_CFG"},  // TI: SmartRF Studio export in TI swrc253e (868 MHz, 25 kHz, 4 kHz)
    {0x2F01, 0x22, 0xFF, "FREQOFF_CFG"},  // TI: frequency offset correction on, loop 1/64 during packet
    {0x2F02, 0x0A, 0xFF, "TOC_CFG"},  // TI: timing offset blocks 16/32 symbols (SmartRF Studio export in TI swrc253e, 4.8 kbit/s block)
    {0x2F0C, 0x6C, 0xFF, "FREQ2"},  // P1: FREQ = 0x6CB0CD: 869.525024 MHz, step 122.1 Hz (eq. 26, 27)
    {0x2F0D, 0xB0, 0xFF, "FREQ1"},  // P1: FREQ[15:8]
    {0x2F0E, 0xCD, 0xFF, "FREQ0"},  // P1: FREQ[7:0]
    {0x2F12, 0x00, 0xFF, "FS_DIG1"},  // TI: SmartRF Studio export in TI swrc253e (868 MHz, 25 kHz, 4 kHz)
    {0x2F13, 0x5F, 0xFF, "FS_DIG0"},  // TI: SmartRF Studio export in TI swrc253e (868 MHz, 25 kHz, 4 kHz)
    {0x2F16, 0x40, 0xFF, "FS_CAL1"},  // TI: SmartRF Studio export in TI swrc253e (868 MHz, 25 kHz, 4 kHz)
    {0x2F17, 0x0E, 0xFF, "FS_CAL0"},  // TI: SmartRF Studio export in TI swrc253e (868 MHz, 25 kHz, 4 kHz)
    {0x2F19, 0x03, 0xFF, "FS_DIVTWO"},  // TI: SmartRF Studio export in TI swrc253e (868 MHz, 25 kHz, 4 kHz)
    {0x2F1B, 0x33, 0xFF, "FS_DSM0"},  // TI: SmartRF Studio export in TI swrc253e (868 MHz, 25 kHz, 4 kHz)
    {0x2F1D, 0x17, 0xFF, "FS_DVC0"},  // TI: SmartRF Studio export in TI swrc253e (868 MHz, 25 kHz, 4 kHz)
    {0x2F1F, 0x50, 0xFF, "FS_PFD"},  // TI: SmartRF Studio export in TI swrc253e (868 MHz, 25 kHz, 4 kHz)
    {0x2F20, 0x6E, 0xFF, "FS_PRE"},  // TI: SmartRF Studio export in TI swrc253e (868 MHz, 25 kHz, 4 kHz)
    {0x2F21, 0x14, 0xFF, "FS_REG_DIV_CML"},  // TI: SmartRF Studio export in TI swrc253e (868 MHz, 25 kHz, 4 kHz)
    {0x2F22, 0xAC, 0xFF, "FS_SPARE"},  // TI: SmartRF Studio export in TI swrc253e (868 MHz, 25 kHz, 4 kHz)
    {0x2F27, 0xB4, 0xFF, "FS_VCO0"},  // TI: SmartRF Studio export in TI swrc253e (868 MHz, 25 kHz, 4 kHz)
    {0x2F32, 0x0E, 0xFF, "XOSC5"},  // TI: SmartRF Studio export in TI swrc253e (868 MHz, 25 kHz, 4 kHz)
    {0x2F36, 0x03, 0xFE, "XOSC1"},  // TI: low phase noise differential buffer; bit 0 is read-only XOSC_STABLE
};
constexpr size_t REGISTER_COUNT = sizeof(REGISTERS) / sizeof(REGISTERS[0]);

}  // namespace p1
