// SPDX-License-Identifier: MIT
// Generated by firmware/tools/s2lp_p1_registers.py; do not edit by hand.
// Profile P1 for the S2-LP on the X-NUCLEO-S2868A2 (f_xo = 50 MHz, f_dig = 25 MHz): values marked P1
// are computed with the DS11896 equations and the ST library searches, ST values come from the
// ST S2-LP library init, reset values are written explicitly. See firmware/README.md.
#pragma once

#include <stddef.h>
#include <stdint.h>

#include "s2lp.h"

namespace p1s2 {

using s2lp::RegisterValue;  // {address, value, verifyMask, name}

constexpr uint32_t F_XO_HZ = 50000000;
constexpr uint8_t BAND_FACTOR = 4;
constexpr uint8_t REF_DIVIDER = 1;
constexpr uint32_t CARRIER_HZ = 869525000;
constexpr uint16_t SYMBOL_RATE = 4800;
constexpr uint16_t DEVIATION_HZ = 4000;
constexpr uint16_t RX_FILTER_HZ = 25481;
constexpr int8_t TX_POWER_DBM = 13;
constexpr uint8_t MAX_PACKET_BYTES = 103;

constexpr RegisterValue REGISTERS[] = {
    {0x00, 0x02, 0xFF, "GPIO0_CONF"},  // P1: GPIO0 (ESP32-S3 GPIO14, J11) = nIRQ, active low; no interrupt unmasked yet
    {0x01, 0xA2, 0xFF, "GPIO1_CONF"},  // reset: GPIO1 (GPIO21) = digital GND
    {0x02, 0x7A, 0xFF, "GPIO2_CONF"},  // P1: GPIO2 (ESP32-S3 GPIO4, J11) = sync word detected, as IOCFG2 on bench A
    {0x03, 0xA2, 0xFF, "GPIO3_CONF"},  // reset: GPIO3 (GPIO42) = digital GND
    {0x05, 0x62, 0xFF, "SYNT3"},  // P1: PLL_CP_ISEL = 3 (VCO 3478 MHz < 3600, f_xo 50 MHz, table 37), BS = 0 (B = 4), SYNT[27:24]
    {0x06, 0x2C, 0xFF, "SYNT2"},  // P1: SYNT = 0x22C7EFA: 869.525003 MHz, step 23.8 Hz (eq. 7)
    {0x07, 0x7E, 0xFF, "SYNT1"},  // P1: SYNT[15:8]
    {0x08, 0xFA, 0xFF, "SYNT0"},  // P1: SYNT[7:0]
    {0x09, 0x2F, 0xFF, "IF_OFFSET_ANA"},  // P1: IF 300 kHz at f_xo 50 MHz (eq. 15; reset value is for 26 MHz)
    {0x0A, 0xC2, 0xFF, "IF_OFFSET_DIG"},  // P1: IF 300 kHz at f_dig 25 MHz (eq. 15)
    {0x0D, 0x00, 0xFF, "CHNUM"},  // reset: channel 0: carrier = base frequency
    {0x0E, 0x92, 0xFF, "MOD4"},  // P1: DATARATE_M = 0x92A7, DATARATE_E = 4: 4800.0 Bd (eq. 14)
    {0x0F, 0xA7, 0xFF, "MOD3"},  // P1: DATARATE_M[7:0]
    {0x10, 0xA4, 0xFF, "MOD2"},  // P1: 2-GFSK BT 0.5, DATARATE_E
    {0x11, 0x01, 0xFF, "MOD1"},  // P1: no PA or frequency interpolation, CONST_MAP 0 (bit 1 = +FDEV), FDEV_E = 1
    {0x12, 0x50, 0xFF, "MOD0"},  // P1: FDEV_M = 80: deviation 4005.4 Hz (eq. 10)
    {0x13, 0x15, 0xFF, "CHFLT"},  // P1: CHFLT_M = 1, CHFLT_E = 5: RX filter 25481 Hz (table 44 x 25/26)
    {0x18, 0x2E, 0xFF, "RSSI_TH"},  // P1: carrier sense at -100 dBm (RSSI_TH - 146; offset not measured, T4)
    {0x2B, 0x80, 0xFF, "PCKTCTRL6"},  // P1: 32-bit sync word, PREAMBLE_LEN[9:8]
    {0x2C, 0x20, 0xFF, "PCKTCTRL5"},  // P1: 32 preamble pairs = 8 bytes
    {0x2D, 0x00, 0xFF, "PCKTCTRL4"},  // P1: 1-byte length field, no address field
    {0x2E, 0x01, 0xFF, "PCKTCTRL3"},  // P1: BASIC packet, normal RX mode (reset value 0x20 is direct through GPIO), MSB first, preamble 1010 = 0xAA
    {0x2F, 0x01, 0xFF, "PCKTCTRL2"},  // P1: variable length: LEN = payload = BODY + CRC (radio.md, F79); no Manchester, no 3-of-6
    {0x30, 0x00, 0xFF, "PCKTCTRL1"},  // P1: chip CRC off (P1 CRC by software), no whitening, TX from FIFO (reset value 0x2C sends PN9), no FEC
    {0x31, 0x00, 0xFF, "PCKTLEN1"},  // P1: TX length MSB
    {0x32, 0x66, 0xFF, "PCKTLEN0"},  // P1: TX length: longest BODY + CRC; the P1 driver sets it per packet
    {0x33, 0xD3, 0xFF, "SYNC3"},  // P1: sync word D3 91 D3 91, byte order on air to be checked against bench A
    {0x34, 0x91, 0xFF, "SYNC2"},  // P1: sync word byte 2
    {0x35, 0xD3, 0xFF, "SYNC1"},  // P1: sync word byte 1
    {0x36, 0x91, 0xFF, "SYNC0"},  // P1: sync word byte 0
    {0x40, 0x40, 0xFF, "PCKT_FLT_OPTIONS"},  // reset: no address filters, CRC filter off
    {0x61, 0x03, 0xFF, "PA_POWER1"},  // ST: PA level for slot 1 (index 7): 29 - 2 x 13 dBm (ST library formula; measure in T4)
    {0x62, 0x07, 0xFF, "PA_POWER0"},  // ST: PA_MAXDBM off, no ramp, DIG_SMOOTH off (FSK), PA_LEVEL_MAX_IDX = 7
    {0x63, 0x01, 0xFF, "PA_CONFIG1"},  // ST: FIR off for FSK (reset 0x03 with FIR_EN cleared)
    {0x64, 0x88, 0xFF, "PA_CONFIG0"},  // ST: PA Bessel filter 12.5 kHz for data rate < 16 kbps (reset 0x8A, PA_FC = 0)
    {0x65, 0xD0, 0xFF, "SYNTH_CONFIG2"},  // P1: PLL_PFD_SPLIT_EN = 0 (table 37)
    {0x6C, 0x45, 0xFF, "XO_RCO_CONF1"},  // reset: PD_CLKDIV = 0: digital clock f_xo / 2 = 25 MHz, needed for 50 MHz
    {0x6D, 0x30, 0xFF, "XO_RCO_CONF0"},  // reset: REFDIV = 0: reference divider off (D = 1)
    {0x76, 0x90, 0xFF, "PM_CONF3"},  // ST: SMPS rate multiplier on, KRM = 0x1000: 3.125 MHz (S2LP::begin)
};
constexpr size_t REGISTER_COUNT = sizeof(REGISTERS) / sizeof(REGISTERS[0]);

}  // namespace p1s2
